### PR TITLE
Fix Catchup

### LINKED ISSUE #97: Problems with catch up
There seems to be some problems with catching up a peer that is behind. As I described on IRC:

> The leader decrements the next_index, and then tries to catch up the follower, which responds that it's still inconsistent, so the leader looks at next_index again (and because of the catch up it's the same again) and decrements it.

(More investigation and notes incoming later)

Related: #55

### PR DESCRIPTION
**Pull request by Hoverbear**
(Closes #97, much more info there)

Steps to reproduce:

* `cd experiments/tmux/hashmap-local-3`
* `./dashboard` to get 4 tabs.
* In *Server 1* `RUST_LOG=raft::consensus=debug ./server 1`
* In *Server 2* `RUST_LOG=raft::consensus=debug ./server 2`
* In *Server 3* `RUST_LOG=raft::consensus=debug ./server 3`
* In *Command Seat* `./put foo bar` a few times (doesn't matter really)
* Look for the leader in the servers, kill it.
* Restart the leader after a moment.
* Observe looping behaivor.

This fixes is by:
* Having `append_entries` carry the entry terms as well.
* Correctly reporting back the right index.

@danburkert please review. :)

### CODE REVIEW

File: src/consensus.rs [hunk 1]
```diff
@@ -231,23 +231,20 @@ impl <L, M> Consensus<L, M> where L: Log, M: StateMachine {
...
-
-                    request.set_prev_log_index(prev_log_index);
-                    request.set_prev_log_term(prev_log_term.into());
-                    request.set_leader_commit(self.commit_index.into());
-
-                    let mut entries = request.init_entries((until_index - from_index) as u32);
-                    for (n, index) in (from_index..until_index).enumerate() {
-                        entries.set(n as u32, self.persistent_log.entry(LogIndex::from(index)).unwrap().1);
-                    }
+                let mut entries = vec![];
```
Comment (tschottdorf) [inline src/consensus.rs]: you already know how many elements you'll add, can you have the vector be allocated with the correct capacity (I'm assuming this isn't happening magically)?

File: src/consensus.rs [hunk 2]
```diff
@@ -231,23 +231,20 @@ impl <L, M> Consensus<L, M> where L: Log, M: StateMachine {
...
+                for index in (from_index .. until_index) {
+                    entries.push(self.persistent_log.entry(LogIndex::from(index)).unwrap())
```
Comment (tschottdorf) [inline src/consensus.rs]: not directly related to this PR, but in the normal case, you're going to read multiple entries. I think it would make sense if the persistent log interface reflected that by taking the format
`entries(lo, hi)` where `hi` is exclusive. So you'd get
`let entries = self.persistent_log.entry(index, until_index)` and the persistent log would be able to help you out a little bit performance wise (on top of the small gain here).

File: src/consensus.rs [hunk 3]
```diff
@@ -302,7 +299,9 @@ impl <L, M> Consensus<L, M> where L: Log, M: StateMachine {
                     if latest_log_index < leader_prev_log_index {
                         scoped_debug!("AppendEntriesRequest: inconsistent previous log index: leader: {}, local: {}",
                                       leader_prev_log_index, latest_log_index);
-                        messages::append_entries_response_inconsistent_prev_entry(self.current_term())
+                        // Reply false if log doesn’t contain an entry at prevLogIndex whose term matches prevLogTerm
```
Comment (tschottdorf) [inline src/consensus.rs]: it doesn't look like you're validating the term here, opposed to what the comment suggests. This is just the case in which the leader tries to append at a position which doesn't match up with the end of our log.

File: src/consensus.rs [hunk 4]
```diff
@@ -313,14 +312,20 @@ impl <L, M> Consensus<L, M> where L: Log, M: StateMachine {
                         if existing_term != leader_prev_log_term {
                             scoped_debug!("AppendEntriesRequest: inconsistent previous log term: leader: {}, local: {}",
                                           leader_prev_log_term, existing_term);
-                            messages::append_entries_response_inconsistent_prev_entry(self.current_term())
+                            // If an existing entry conflicts with a new one (same index but different terms),
+                            // delete the existing entry and all that follow it
+                            messages::append_entries_response_inconsistent_prev_entry(self.current_term(),
+                                leader_prev_log_index)
```
Comment (tschottdorf) [inline src/consensus.rs]: I must be missing something - at this point I would expect something like `self.persistent_log.append_entries(leader_prev_log_index+1, vec![]);` to clear out the log, but I don't see that happening.

File: src/consensus.rs [hunk 5]
```diff
@@ -400,12 +405,12 @@ impl <L, M> Consensus<L, M> where L: Log, M: StateMachine {
                 self.leader_state.set_match_index(from, follower_latest_log_index);
                 self.advance_commit_index(actions);
             }
-            Ok(append_entries_response::Which::InconsistentPrevEntry(..)) => {
+            Ok(append_entries_response::Which::InconsistentPrevEntry(index)) => {
```
Comment (tschottdorf) [inline src/consensus.rs]: can you just rename `index`->`next_index` and save the `let next_index = index;` below?

File: src/consensus.rs (hunk 4 above)
Comment (tschottdorf) [inline src/consensus.rs]: Ah, I see. Maybe update the comment so that it reflects that we're telling the leader to overwrite our log beginning after `leader_prev_log_index`.

File: src/consensus.rs [hunk 6]
```diff
@@ -437,24 +442,23 @@ impl <L, M> Consensus<L, M> where L: Log, M: StateMachine {
...
+            let message = messages::append_entries_request(
+                local_term.into(),
+                prev_log_index.into(),
+                prev_log_term.into(),
+                &entries,
+                self.commit_index.into());
+
             self.leader_state.set_next_index(from, local_latest_log_index + 1);
-            actions.peer_messages.push((from, Rc::new(message)));
+            actions.peer_messages.push((from, message));
```
Comment (tschottdorf) [inline src/consensus.rs]: the part of the diff above looks like it duplicates code with your change in `peer_connection_reset`. Seems worth refactoring.

File: src/consensus.rs (hunk 4 above)
Comment (tschottdorf) [inline src/consensus.rs]: Can you check what happens when a node becomes leader after rebooting and losing in-memory state about it's peers? I **think** it'll send an append request for its inaugural proposal with `leader_prev_log_index=0`, which, if rejected by the follower (for instance because of a log divergence) would let the leader believe that the peer doesn't have a log at all.
If that's true, should special-case `0` so that the leader simply tries the previous log entry in such a case. And either way, would be good to have a test for this.

File: src/consensus.rs [hunk 7]
```diff
@@ -231,23 +231,20 @@ impl <L, M> Consensus<L, M> where L: Log, M: StateMachine {
                         self.persistent_log.entry(LogIndex(prev_log_index)).unwrap().0
                     };
 
-                let mut message = MallocMessageBuilder::new_default();
```
Comment (danburkert) [inline src/consensus.rs]: Is this just cleanup, or is it related to the bug? (the former is fine, I just want to make sure I understand what's going on)

Comment (tschottdorf) [inline src/consensus.rs]: this is almost certainly just cleanup.

Comment (danburkert) [inline src/consensus.rs]: I see now that it has to do with adding `Entry`.

File: src/consensus.rs (hunk 4 above)
Comment (tschottdorf) [inline src/consensus.rs]: answered by @danburkert:

>
[9:05pm] tschottdorf: dcb: let from_index = Into::<u64>::into(self.leader_state.next_index(&peer));
[9:06pm] tschottdorf: I don’t see anything that initializes next_index(&peer) except as a reaction to an append. What is it on the first append?
[9:06pm] dcb: tschottdorf: as per the paper, it's set to the leader's latest index + 1 when the leader is elected
[9:06pm] dcb: this happens in state.rs
[9:09pm] tschottdorf: ah, that’s what I was looking for.
[9:09pm] tschottdorf: ok, I’m with you now

So all is well.

**Comment by danburkert** [comment]
Looks good to me!  r+ once you take in @tschottdorf's comments.

File: src/consensus.rs (hunk 1 above)
Comment (Hoverbear) [inline src/consensus.rs]: We could totally use `Vec::with_capacity()`! Good idea!

File: src/consensus.rs (hunk 4 above)
Comment (Hoverbear) [inline src/consensus.rs]: Okay, no changes here then!

File: src/consensus.rs (hunk 7 above)
Comment (Hoverbear) [inline src/consensus.rs]: Yes, and a bit of cleanup. :)

File: src/consensus.rs (hunk 2 above)
Comment (Hoverbear) [inline src/consensus.rs]: Let's roll this into a seperate issues since this is an API change.

File: src/consensus.rs (hunk 6 above)
Comment (Hoverbear) [inline src/consensus.rs]: This would be enabled #101. :)

File: src/consensus.rs (hunk 3 above)
Comment (Hoverbear) [inline src/consensus.rs]: Actually this comment is wrong as it's checking for the index!

**Comment by danburkert** [comment]
@homu r+

**Comment by Hoverbear** [comment]
@homu retry

**Comment by Hoverbear** [comment]
@homu retry

**Comment by Hoverbear** [comment]
@homu r=danburkert
